Adding ability to resource zshrc after it's been updated

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,8 +1,17 @@
 ###############
 # Update repo #
 ###############
-git --git-dir=$HOME/dotfiles/.git fetch --all > /dev/null && git --git-dir=$HOME/dotfiles/.git merge --ff-only > /dev/null || echo "$HOME/dotfiles is dirty and cannot be fast-forwarded."
+if [[ -z "${DOTFILES_REPOSITORY_UPDATED}" ]]; then 
+  # Update the repository then re-source the file to pick up the changes
+  git --git-dir=$HOME/dotfiles/.git fetch --all > /dev/null && git --git-dir=$HOME/dotfiles/.git merge --ff-only > /dev/null || echo "$HOME/dotfiles is dirty and cannot be fast-forwarded."
+  DOTFILES_REPOSITORY_UPDATED=true
+  source ${0:a}
+  return 0
+fi
 
+######################
+# OS dependent files #
+######################
 if [[ `uname` == 'Darwin' ]]; then
     source $(dirname "${(%):-%N}")/mac.zsh
 fi
@@ -11,9 +20,10 @@ if [[ `uname` == 'Linux' ]]; then
     source $(dirname "${(%):-%N}")/linux.zsh
 fi
 
-##################
-# Powerlevel 10k #
-##################
+#################################
+# Powerlevel 10k instant prompt #
+#################################
+
 # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
 # Initialization code that may require console input (password prompts, [y/n]
 # confirmations, etc.) must go above this block; everything else may go below.
@@ -31,8 +41,14 @@ setopt inc_append_history share_history hist_ignore_space
 
 setopt auto_pushd
 
+###########
+# Antigen #
+###########
 source $(dirname "${(%):-%N}")/antigen.zsh
 
+##############
+# Completion #
+##############
 autoload -Uz compinit && compinit
 
 source $(dirname "${(%):-%N}")/git.zsh
@@ -42,5 +58,3 @@ export EDITOR=$(which vi)
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
-
-
