Adding the ability to update the repository

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,3 +1,7 @@
+###############
+# Update repo #
+###############
+git --git-dir=$HOME/dotfiles/.git fetch --all > /dev/null && git --git-dir=$HOME/dotfiles/.git merge --ff-only > /dev/null || echo "$HOME/dotfiles is dirty and cannot be fast-forwarded."
 
 if [[ `uname` == 'Darwin' ]]; then
     source $(dirname "${(%):-%N}")/mac.zsh
